name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create file
      run: echo "Run GitHub Actions" > actionsFileOutput.txt
    - name: Upload file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ios_failed
        path: 'actionsFileOutput.txt'
